.SUFFIXES:

CXX =
CXX += c++
CXX += -std=c++11

COMPILER =
COMPILER += -Wall
COMPILER += -g

LINKER =
LINKER += -llo
LINKER += -ltcc

_: per-sample-c-client

%.o: %.cpp
	$(CXX) $^ -c $(COMPILER)

per-sample-c-client: per-sample-c-client.cpp
	$(CXX) $^ -o $@ $(LINKER)

clean:
	rm -f per-sample-c-client
	rm -f per-sample-c-client.o
